name: Github actions tutorial

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  mascot: Mona
  owner: Kings

jobs:
  deploy:
    name: "Deploy-staging"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout and Clone Repo
      uses: actions/checkout@v3
      with: 
        repository: ${{ github.repository }}

    - name: Extract branch name
      run: |
        echo "SHORT_REF=$(echo {$GITHUB_REF} | awk -F '/' '{print $3}')" >> $GITHUB_ENV

    - name: Extract the Github sha
      run: |
        echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
    - name: Check how to run on a single line
      run: echo "MYDIR=$(pwd | awk -F '/' '{print $4}')" >> GITHUB_ENV
      
    - name: Run Multiple commands
      run:
          pwd
          ls
    - name: Echo env variables
      run: |
          echo 'Hi ${{ env.mascot }}'
          echo 'Hi ${{ env.owner }} you did a good job'
